version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        PYTHON_VERSION: 3.9 # you can change it to 3.9, 3.10 3.11, 3.12
    ports:
      - 3001:3000
      - 8000:8000
    volumes:
      - ./.aic:/app/.aic
      - ./aiconsole:/app/aiconsole
      - ./bin:/app/bin
      - ./tests:/app/tests
      - ./web:/app/web
      - ./agents:/app/agents
      - ./materials:/app/materials
      - ./poetry.lock:/app/poetry.lock
      - ./pyproject.toml:/app/pyproject.toml
    command: "poetry run aiconsole-dev"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
