name = "Materials List"
version = "0.0.2"
usage = "Contains an index of materials. Do not use if not tasked to list materials or learning about capabilities of this AIConsole instance."
usage_examples = []
default_status = "enabled"
content_type = "dynamic_text"
content_dynamic_text = """
from aiconsole import projects

async def content(context):
    newline = "\\\\n"
    materials_list = newline.join(f"* {material.id} - {material.usage}" for material in projects.get_project_materials().all_assets())
    return f"# List of Materials{newline}{newline}Available materials:{newline}{materials_list}"
"""
