name: Upload Electron Binaries to Github

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            # { name: 'linux', image: 'ubuntu-latest' },
            # { name: 'windows', image: 'windows-latest' },
            { name: 'macos-x86', image: 'macos-latest' },
            { name: 'macos-arm64', image: 'macos-latest-xlarge' }, 
          ]

    runs-on: ${{ matrix.os.image }}

    steps:
      - name: Github checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: cd electron && yarn run publish